# SnowFox Kitty Theme
background #11111b
foreground #cdd6f4
window_padding_width 12
window_padding_height 12

# Cursor
cursor     	  #9d6fe8
cursor_text_color #11111b

# Auswahl
selection_background #8139e8
selection_foreground #ffffff

background_opacity 0.95
dynamic_background_opacity yes

# Farben (passend zur SnowFox-Palette)
color0  #1e1e2e
color1  #e87a7a
color2  #89c98a
color3  #e8c97a
color4  #9d6fe8
color5  #b899ff
color9  #e87a7a
color10 #89c98a
color11 #e8c97a
color12 #9d6fe8
color13  #b899ff
color14 #89dceb
color15 #ffffff

# Font
font_family      JetBrainsMono Nerd Font
font_size        11.0
