# SnowFoxOS — NVIDIA Konfiguration
# Nouveau muss blacklisted sein
blacklist nouveau

# Power Management
options nvidia NVreg_TemporaryFilePath=/var/tmp
options nvidia NVreg_EnableS0ixPowerManagement=0
options nvidia NVreg_PreserveVideoMemoryAllocations=1

# KMS aktivieren (benoetigt fuer Wayland-Kompatibilitaet und besseres Suspend)
options nvidia-drm modeset=1
