# SnowFoxOS — NVIDIA Configuration
# Nouveau must be blacklisted
blacklist nouveau

# Power Management
options nvidia NVreg_TemporaryFilePath=/var/tmp
options nvidia NVreg_EnableS0ixPowerManagement=0
options nvidia NVreg_PreserveVideoMemoryAllocations=1

# Enable KMS (required for Wayland compatibility and better suspend)
options nvidia-drm modeset=1
